OpenFn/adaptors

packages/primero/src/Adaptor.js

Update the helper function `upsertCase` to use `data` instead of `state.data` when updating cases
Fixes #30

change `state.data` in `upsertCase` to `data`

---

packages/sftp/credential-schema.json

Added `credential-schema.json`

add credential schema

---

.changeset/ninety-eels-divide.md
README.md
packages/beyonic/LICENSE
packages/beyonic/LICENSE.LESSER
packages/beyonic/README.md
packages/beyonic/credential-schema.json
packages/beyonic/package.json
packages/beyonic/src/Adaptor.js
packages/beyonic/src/Client.js
packages/beyonic/src/index.js
pnpm-lock.yaml

Please do review, merge, and archive [this adaptor](https://github.com/openfn/language-beyonic) accordingly

Move language-beyonic to adaptors/packages/beyonic

---

.changeset/mean-rockets-heal.md
README.md
packages/postgresql/LICENSE
packages/postgresql/LICENSE.LESSER
packages/postgresql/README.md
packages/postgresql/ast.json
packages/postgresql/credential-schema.json
packages/postgresql/package.json
packages/postgresql/src/Adaptor.js
packages/postgresql/src/index.js
packages/postgresql/test/ClientFixtures.js
packages/postgresql/test/index.js
pnpm-lock.yaml

Please review, merge, and archive [language-postgresql](https://github.com/OpenFn/language-postgresql)

Migrate postgresql

---

.changeset/good-bears-brush.md
packages/asana/.travis.yml
packages/asana/LICENSE
packages/asana/LICENSE.LESSER
packages/asana/README.md
packages/asana/ast.json
packages/asana/credential-schema.json
packages/asana/package.json
packages/asana/src/Adaptor.js
packages/asana/src/index.js
packages/asana/test/ClientFixtures.js
packages/asana/test/index.js
pnpm-lock.yaml

Please review, merge and archive [language-asana](https://github.com/OpenFn/language-asana)

Migrate asana

---

.changeset/warm-dolphins-sell.md
packages/primero/src/Adaptor.js

@mtuchi , this may be necessary

only check for withReferrals if options is present

---

.changeset/smooth-suits-applaud.md
packages/salesforce/.flowconfig
packages/salesforce/LICENSE
packages/salesforce/LICENSE.LESSER
packages/salesforce/README.md
packages/salesforce/ast.json
packages/salesforce/configuration-schema.json
packages/salesforce/package.json
packages/salesforce/src/Adaptor.js
packages/salesforce/src/FakeAdaptor.js
packages/salesforce/src/index.js
packages/salesforce/test/Adaptor.test.js
packages/salesforce/test/CompositionExamples.test.js
packages/salesforce/test/json_reference.test.js
packages/salesforce/test/macros_test.sjs
packages/salesforce/test/nestedTestData.json
packages/salesforce/test/testData.json
pnpm-lock.yaml

Please review, merge, and archive [this repo](https://github.com/OpenFn/language-salesforce).

Migrate SalesForce

---

.changeset/empty-paws-draw.md
.changeset/quick-frogs-tell.md
packages/http/README.md
packages/primero/src/Adaptor.js

Added `metadata` in `getCases`  state

`primero` Add `metadata` in `getCases` state

---

.changeset/moody-pears-dance.md
packages/ocl/LICENSE
packages/ocl/LICENSE.LESSER
packages/ocl/README.md
packages/ocl/ast.json
packages/ocl/configuration-schema.json
packages/ocl/package.json
packages/ocl/src/Adaptor.js
packages/ocl/src/index.js
packages/ocl/test/ClientFixtures.js
packages/ocl/test/index.js
pnpm-lock.yaml

Please review, merge, and archive [language-ocl](https://github.com/OpenFn/language-ocl)

Migrate OCL

---

.changeset/witty-ways-pretend.md
packages/kobotoolbox/LICENSE
packages/kobotoolbox/LICENSE.LESSER
packages/kobotoolbox/README.md
packages/kobotoolbox/configuration-schema.json
packages/kobotoolbox/package.json
packages/kobotoolbox/src/Adaptor.js
packages/kobotoolbox/src/index.js
packages/kobotoolbox/test/ClientFixtures.js
packages/kobotoolbox/test/index.js
pnpm-lock.yaml

Please review, merge, and archive [language-kobotoolbox](https://github.com/OpenFn/language-kobotoolbox)

Migrate kobotoolbox

---

.changeset/smooth-deers-prove.md
.changeset/tricky-dots-melt.md
packages/asana/package.json
packages/beyonic/package.json
packages/commcare/package.json
packages/common/package.json
packages/dhis2/package.json
packages/fhir/package.json
packages/googlesheets/package.json
packages/http/package.json
packages/kobotoolbox/package.json
packages/mssql/package.json
packages/ocl/package.json
packages/postgresql/package.json
packages/primero/package.json
packages/salesforce/package.json
packages/sftp/package.json
packages/template/package.json
pnpm-lock.yaml
tools/migrate/src/update-package.ts

Revert all changes to main in https://github.com/OpenFn/adaptors/pull/97 (including in the migration tool).
Fixes #114 #115

Fix `cjs exports` in every package

---

tools/build/src/commands/docs.ts
tools/build/src/util/docs-template.hbs

Enhance markdown docs

---

.github/workflows/docs.sh
.github/workflows/docs.yaml
packages/dhis2/README.md
packages/fhir/README.md
packages/googlesheets/README.md
packages/http/README.md
packages/primero/README.md
packages/sftp/README.md
packages/template/README.md
tools/build/src/commands/docs.ts
tools/build/src/util/docs-template.hbs

Fix packages readme docs, building docs and push changes to `docs` branch

GitHub action for building docs

---

README.md

Add a high-level, single-sentence summary of what this PR changes.
Reference any related issues here.

Add important notes

---

.changeset/many-bottles-applaud.md
packages/kobotoolbox/ast.json
packages/kobotoolbox/src/Adaptor.js
packages/kobotoolbox/src/index.js

Add `fn` function from `language-common` and fix `index.js` exports

Fix `kobotoolbox`

---

.changeset/polite-shoes-fold.md
packages/progres/LICENSE
packages/progres/LICENSE.LESSER
packages/progres/README.md
packages/progres/ast.json
packages/progres/configuration-schema.json
packages/progres/package.json
packages/progres/src/Adaptor.js
packages/progres/src/index.js
packages/progres/test/ClientFixtures.js
packages/progres/test/index.js
pnpm-lock.yaml

This PR migrates the language-progres adaptor inside this adaptors monorepo.
#50

Migrate Progres

---

.changeset/tall-rats-marry.md
packages/mssql/src/Adaptor.js

Fix `language-mssql` connection issue and flatten rows' response
Reference any related issues here.

Fix `language-mssql`

---

.changeset/rare-kings-repair.md
packages/twilio/LICENSE
packages/twilio/LICENSE.LESSER
packages/twilio/README.md
packages/twilio/ast.json
packages/twilio/credential-schema.json
packages/twilio/package.json
packages/twilio/src/Adaptor.js
packages/twilio/src/index.js
packages/twilio/test/ClientFixtures.js
packages/twilio/test/index.js
pnpm-lock.yaml

Migrated `language-twilio` 
#50 

Migrate twilio

---

.changeset/quiet-months-retire.md
packages/surveycto/LICENSE
packages/surveycto/LICENSE.LESSER
packages/surveycto/README.md
packages/surveycto/ast.json
packages/surveycto/configuration-schema.json
packages/surveycto/package.json
packages/surveycto/src/Adaptor.js
packages/surveycto/src/index.js
packages/surveycto/test/ClientFixtures.js
packages/surveycto/test/index.js
pnpm-lock.yaml

Migrate `language-surveycto`
#50 

Migrate `surveycto`

---

.changeset/spicy-wolves-carry.md
packages/telerivet/LICENSE
packages/telerivet/LICENSE.LESSER
packages/telerivet/README.md
packages/telerivet/ast.json
packages/telerivet/configuration-schema.json
packages/telerivet/package.json
packages/telerivet/src/Adaptor.js
packages/telerivet/src/Client.js
packages/telerivet/src/index.js
packages/telerivet/test/Client.test.js
packages/telerivet/test/ClientFixtures.js
packages/telerivet/test/index.js
pnpm-lock.yaml

`language-telerivet` migration to monorepo
#50 

Migrate `telerivet`

---

.changeset/fresh-eyes-wash.md
packages/zoho/LICENSE
packages/zoho/LICENSE.LESSER
packages/zoho/README.md
packages/zoho/ast.json
packages/zoho/configuration-schema.json
packages/zoho/package.json
packages/zoho/src/Adaptor.js
packages/zoho/src/Client.js
packages/zoho/src/index.js
packages/zoho/test/Client.test.js
packages/zoho/test/ClientFixtures.js
packages/zoho/test/index.js
pnpm-lock.yaml

Migrate `zoho`

---

.changeset/brown-geckos-speak.md
packages/vtiger/LICENSE
packages/vtiger/LICENSE.LESSER
packages/vtiger/README.md
packages/vtiger/ast.json
packages/vtiger/configuration-schema.json
packages/vtiger/package.json
packages/vtiger/src/Adaptor.js
packages/vtiger/src/index.js
packages/vtiger/test/ClientFixtures.js
packages/vtiger/test/index.js
pnpm-lock.yaml

`language-vtiger` migration
#50 

Migrate `vtiger`

---

.changeset/bright-jeans-speak.md
packages/facebook/LICENSE
packages/facebook/LICENSE.LESSER
packages/facebook/README.md
packages/facebook/ast.json
packages/facebook/configuration-schema.json
packages/facebook/package.json
packages/facebook/src/Adaptor.js
packages/facebook/src/index.js
packages/facebook/test/ClientFixtures.js
packages/facebook/test/index.js
pnpm-lock.yaml

Migrate `language-facebook`
#50 

Migrate `facebook`

---

.changeset/eleven-ads-taste.md
.changeset/moody-grapes-peel.md
packages/cartodb/package.json
packages/godata/package.json
packages/mailchimp/package.json
packages/openhim/package.json
packages/rapidpro/package.json
packages/telerivet/package.json
packages/zoho/package.json
pnpm-lock.yaml

Version bump to fix security vulnerabilities in `Axios` and `superagent`. See dependant alerts https://github.com/OpenFn/adaptors/security/dependabot

Security fixes for `Axios` and `superagent`

---

.changeset/rude-badgers-hammer.md
packages/bigquery/src/index.js
packages/commcare/src/index.js

Fixed exports for `big-query` and `commcare`  in `index.js`

Fix exports

---

tools/build/src/commands/docs.ts

Add `configuration-schema` in docs build bundle
In the build tool for docs added a `configuration-schema` file
#178

add configuration-schema in docs

---

.changeset/happy-jokes-trade.md
packages/dhis2/README.md

Add replace `sample state` with `configuration`

Update `dhis2` readme

---

.changeset/tricky-ducks-lick.md
packages/maximo/configuration-schema.json
packages/salesforce/configuration-schema.json

@mtuchi , would you mind versioning and releasing these when you get a chance? thank you!

fix schemas for SF and maximo

---

.changeset/chatty-phones-listen.md
packages/mssql/package.json
pnpm-lock.yaml

I have updated the versions for `requests` and `common`

`mssql` dependencies version bumps

---

.changeset/few-badgers-burn.md
.changeset/great-shoes-travel.md
.changeset/tidy-chicken-float.md
packages/bigquery/package.json
packages/magpi/package.json
packages/mssql/package.json
pnpm-lock.yaml

Update dependencies
Dependabot alert [15](https://github.com/OpenFn/adaptors/security/dependabot/15), [14](https://github.com/OpenFn/adaptors/security/dependabot/14)

Dependencies security fixes

---

.changeset/thin-books-destroy.md
packages/commcare/package.json
pnpm-lock.yaml

Update dependencies to address the security alert https://github.com/OpenFn/adaptors/security/dependabot/16 for `commcare` 

update `commcare` dependencies

---

.changeset/modern-houses-happen.md
packages/sftp/ast.json
packages/sftp/package.json
packages/sftp/src/Adaptor.js
pnpm-lock.yaml

Add a parsing option in `getCSV` helper function for converting `csv` to `json`
This is related to this PR #182 

Add `csvtojson` in `sftp`

---

.changeset/neat-bikes-retire.md
.changeset/sharp-timers-shave.md
.changeset/slow-fishes-cheer.md
packages/dhis2/src/Utils.js
packages/mssql/package.json
packages/openmrs/src/Adaptor.js
packages/openmrs/src/Utils.js
pnpm-lock.yaml

Improved logs output for `dhis2` and `openMRS` adaptor, Remove unused dependency in `mssql` adaptor
This PR fixes https://github.com/OpenFn/adaptors/security/dependabot/13

minor improvements

---

.changeset/twenty-pianos-vanish.md
packages/fhir/ast.json
packages/fhir/configuration-schema.json
packages/fhir/package.json
packages/fhir/src/Adaptor.js
packages/fhir/src/Utils.js
packages/fhir/test/index.js
packages/template/src/Adaptor.js
pnpm-lock.yaml

Add a new function `get()`, Update `configuration-schema.json` to use `baseUrl` instead of `resource` and add `apiPath`.
I also fixed `axios` config for `create()` and remove unused code for both  `create()` and `createTransactionBundle()`
I also add `handleResponse` and `handleError` in `Utils.js`

`fhir` improvements

---

.changeset/gold-actors-divide.md
packages/openmrs/src/Adaptor.js
packages/openmrs/src/Utils.js

Replace `throw new Error()` with `console.log()` when we have `0 results returned` 

`OpenMRS` improvements

---

.changeset/tame-eyes-march.md
packages/ocl/ast.json
packages/ocl/package.json
packages/ocl/src/Adaptor.js
packages/ocl/src/Util.js
pnpm-lock.yaml

Based on the `OCL` API structure, i envision the following helper function and a configuration-schema
```
// https://api.openconceptlab.org/orgs/MSFOCG/collections/lime-demo/concepts/
// https://api.openconceptlab.org/orgs/MSFOCG/sources/DHIS2DataElements/concepts/
// https://api.openconceptlab.org/orgs/MSFOCG/sources/OpenMRS/mappings/
// https://api.openconceptlab.org/orgs/MSFOCG/collections/lime-demo/references/
```
`getSource(path, query, callback);` , `getCollection(path, query, callback);`
Eg's: 
- getSource("DHIS2DataElements/concepts/");
- getSource("DHIS2DataElements/mappings/");
- getCollection('lime-demo/mappings');
- getCollection('lime-demo/concepts');
- getCollection('lime-demo/references');
Configuration 
```
{
"baseUrl": "https:api.openconceptlab.org",
"owner": "MSFOCG"
} …
```

`ocl` improvements

---

packages/ocl/src/Util.js

`ocl` fix get request

---

.changeset/silent-flowers-hope.md
packages/msgraph/src/Adaptor.js

Export `parseCsv` from `language-common`

`msgraph` add `parseCsv`

---

.changeset/stale-ducks-invent.md
packages/dhis2/src/Adaptor.js

Improve `dhis2` error logs response by return the whole `response.data` 

Improve `dhis2` error response

---

.changeset/old-mirrors-build.md
packages/msgraph/src/Utils.js

Update url reassignment in request util

`msgraph` update request url

---

.changeset/stale-birds-lick.md
packages/commcare/package.json
pnpm-lock.yaml

Update `xlsx` package in commcare to use `https://cdn.sheetjs.com/xlsx-0.19.3/xlsx-0.19.3.tgz` as [recommended in this post](https://github.com/SheetJS/sheetjs/issues/2822#issuecomment-1536025937) 
Fixes #327 

`commcare` update xlsx

---

.changeset/chatty-ladybugs-beg.md
packages/salesforce/package.json
pnpm-lock.yaml

Update `jsforce` to latest `v1.11.1` and remove unused packages. Fixes #326 

`saleforce` update jsforce

---

.changeset/forty-bees-sit.md
packages/nexmo/package.json
packages/nexmo/src/Adaptor.js
pnpm-lock.yaml

Removed unused packages and update `nexmo` package to use the latest version `v2.9.1`. Also add `expandReferences` on `sendSMS` params. Fixes #329 

Nexmo security patch

---

.changeset/rich-pianos-exercise.md
packages/msgraph/package.json
packages/msgraph/src/Utils.js
pnpm-lock.yaml

Add support for stream in `util/request`. This will help with fetching files as stream which is efficient when fetching huge files 

`msgraph` support stream

---

packages/mongodb/CHANGELOG.md
packages/mongodb/package.json

Bump version of mongo ready for release.

Mongo Release

---

.changeset/empty-moles-tap.md
packages/ocl/ast.json
packages/ocl/src/Adaptor.js

Add `fn` function in `language-ocl`

Add `fn` ocl

---

.changeset/brave-apes-provide.md
packages/common/package.json
packages/common/src/Adaptor.js
packages/common/test/index.test.js
pnpm-lock.yaml

This PR add a `validate(schema, data)` function to the common adaptor. It is designed to validate JSON against a JSON schema.
I won't explain the functionality at length here - docs in the PR should do that for me.
A couple of notes though:
* The function is designed to use `state.data` and `state.schema`, but you can override both values
* Schema can be a string URL to an externally hosted JSON schema
* We use `ajv` do the the actual validation. `ajv` is a code generator: given a schema, it'll generate a function to validate it. This should be safe in both the old and new runtimes. So far as I can tell the only security concern is poorly performing regex, which frankly means you're using a bad schema. `ajv` does not allow arbitrary code injection and does not look like a sandbox escape …

common: JSON schema validation

---

.changeset/eight-bulldogs-whisper.md
packages/mailchimp/configuration-schema.json

Modify the `configuration-schema` for `Mailchimp` adaptor.

Update mailchimp configuration schema

---

.changeset/metal-timers-tease.md
packages/mailchimp/src/Adaptor.js

Add `console.log` on a `request` and fix ast warnings

Add logs in `mailchimp`

---

.changeset/weak-coins-jam.md
packages/salesforce/ast.json
packages/salesforce/src/Adaptor.js

Add a `bulkQuery(query, callback)`. A function that allows user to query records in bulk  

`salesforce` Add `bulkQuery()` function

---

.changeset/cuddly-hats-invent.md
packages/salesforce/ast.json
packages/salesforce/src/Adaptor.js

Add a `options` in `bulkQuery` function 

add options in `bulkQuery()`

---

.changeset/yellow-suits-tie.md
packages/openspp/CHANGELOG.md
packages/openspp/package.json
packages/openspp/src/Adaptor.js

Update `spp date time now string` format. @nhatnm0612 This PR addresses your https://github.com/OpenFn/adaptors/pull/436#discussion_r1397038920

`spp` update date time string format

---

.changeset/wild-parents-think.md
packages/openspp/CHANGELOG.md
packages/openspp/ast.json
packages/openspp/package.json
packages/openspp/src/Adaptor.js

New release for `openspp` adaptor. `@openfn/language-openspp@1.2.0`
Ref #439

New release for `openspp` adaptor 

---

packages/template/CHANGELOG.md
packages/template/package.json

This PR creates an empty release on `template`.
When it is merged into master, it should deploy and notify to slack.

Test Autodeploy

---

README.md

update readme with new release stuff

---

.github/workflows/docs.yaml

fix node version on docs action

---

.changeset/honest-glasses-drum.md
packages/salesforce/CHANGELOG.md
packages/salesforce/ast.json
packages/salesforce/package.json
packages/salesforce/src/Adaptor.js

Add `jsdoc` for search query API limits and improved `bulk()` and `bulkQuery()` jsdocs 
Using `@throws` to describe deferent API limits
Closes #501 #481 

`salesforce` API limits

---

.changeset/empty-paws-move.md
packages/salesforce/CHANGELOG.md
packages/salesforce/package.json
packages/salesforce/src/Adaptor.js

Add a salesforce response even if we don't have records 

Update salesforce `query()` function

---

.changeset/tame-parrots-complain.md
packages/commcare/ast.json
packages/commcare/src/Adaptor.js

Commcare adaptor fixes
A few fixes for `commcare` adaptor
#591 

Commcare adaptor fixes

---

packages/http/CHANGELOG.md
packages/http/package.json
pnpm-lock.yaml

release: http@6.2.3

---

.changeset/green-monkeys-compete.md
packages/postgresql/ast.json
packages/postgresql/src/Adaptor.js

Update all functions to use util `exapandReferences` and add `composeNextState` in `findValue` function
- Ref #604 

Update `postgresql` functions to use util `expandReference`

---

packages/cartodb/CHANGELOG.md
packages/cartodb/package.json

Trying to force release  cartodb

cartodb 0.4.0

---

packages/testing/.eslintrc.json
packages/testing/CHANGELOG.md
packages/testing/LICENSE
packages/testing/LICENSE.LESSER
packages/testing/README.md
packages/testing/ast.json
packages/testing/configuration-schema.json
packages/testing/package.json
packages/testing/src/Adaptor.js
packages/testing/src/index.js
pnpm-lock.yaml

Test adaptor

---

.changeset/flat-games-matter.md
.changeset/odd-eggs-retire.md
packages/common/ast.json
packages/common/src/Adaptor.js
packages/common/src/util/index.js
packages/common/test/index.test.js
packages/dhis2/ast.json
packages/dhis2/src/Adaptor.js
packages/http/ast.json
packages/http/src/Adaptor.js
packages/kobotoolbox/ast.json
packages/kobotoolbox/src/Adaptor.js
packages/postgresql/ast.json
packages/postgresql/src/Adaptor.js
packages/salesforce/ast.json
packages/salesforce/src/Adaptor.js

Add a `group()` operation in language-common with unit test
Ref #605

Add  `group()` operation in common

---

.changeset/nice-pianos-teach.md
.github/workflows/ci.yaml
.github/workflows/docs.yaml
.github/workflows/publish.yaml
packages/mssql/CHANGELOG.md
packages/mssql/configuration-schema.json
packages/mssql/package.json

Add `title` and `description` for port configuration 
Ref #630 

`mssql` update port configuration-schema

---

.changeset/empty-forks-cheer.md
packages/commcare/ast.json
packages/commcare/src/Adaptor.js

Add a `cursor()` and `dateFns()` function from `@openfn/language-common`

`commcare` Add cursor function 

---

packages/redis/ast.json
packages/redis/src/Adaptor.js
packages/redis/src/Utils.js
packages/redis/test/Adaptor.test.js

Add a  `jGet(key: string)`. Ref #714 
**Notes**
changeset is in `release/redis` branch

`redis` Add `jGet` function

---

.changeset/thick-roses-juggle.md
packages/mssql/CHANGELOG.md
packages/mssql/package.json
packages/mssql/src/Adaptor.js

`mssql` use reject instead of throw

---

.changeset/odd-shrimps-relax.md
packages/openmrs/CHANGELOG.md
packages/openmrs/package.json
packages/openmrs/src/Adaptor.js
packages/openmrs/test/fixtures.json
packages/openmrs/test/index.test.js

Remove `prepareNextState` on the upsert operation  since it will be handled in `update` or `create` operation. I have also added 

`openmrs` update upsert operation

---

.changeset/kind-students-sleep.md
packages/hive/package.json
pnpm-lock.yaml

Update `hive-driver ` package to `1.0.0`
Fixes
- https://github.com/OpenFn/adaptors/security/dependabot/96
- Recursively update `ws`, `pnpm update ws -r`
- Then `pnpm i && pnpm build`
- Then `pnpm test`

`hive` update `hive-driver` package

---

packages/fhir-ndr-et/CHANGELOG.md
packages/fhir-ndr-et/package.json
packages/fhir-ndr-et/src/builders.js

Update the spec and rebuild the jembi adaptor.
This is blocking other packages from being published.

fhir-ndr-et: bump version

---

README.md

An updated version of the main adaptor READme to reflect the new changes on how to work with a new adaptor
Fixes #

Adaptors: Update readMe

---

packages/collections/CHANGELOG.md
packages/collections/package.json
packages/collections/src/collections.js
packages/collections/src/mock.js
packages/collections/test/Adaptor.test.js
packages/collections/test/mock/server.test.js

Fixes support for delete (at the time of writing this isn't working on Lightning, I've flagged it over in the Lightning PR)

Collections 0.4

---

.changeset/weak-years-check.md
packages/dhis2/CHANGELOG.md
packages/dhis2/ast.json
packages/dhis2/package.json
packages/dhis2/src/Adaptor.js

Fix example links in dhis2 docs
Note that we cannot nest `{@link}` tags inside examples.
Fixes #854 

dhis: fix docs

---

packages/collections/CHANGELOG.md
packages/collections/package.json
packages/collections/src/mock.js

Collections: expose mock agent

---

packages/gmail/README.md

@decarteret I've restructured and lightly redrafted the readme to make it a little clearer.
We use the word `configuration` in a very specific sense (as in, the configuration object on state), so I've edited carefully around the user of that word.
I've also tried to put broader introductory stuff up at the top of the readme to help orientation, with finer details further down.
Please merge this if you're happy!

Gmail: update readme

---

packages/salesforce/ast.json
packages/salesforce/package.json
packages/salesforce/src/Adaptor.js
pnpm-lock.yaml

This PR updates salesforce to latest common (and tidies up some stuff)

Salesforce: update common

---

tools/generate/template/src/Adaptor.js

1. little bits of leftover callback documentation
2. cleaning up the `data` to `body` transition

more tidying up in generator

---

.changeset/curly-dancers-stare.md
packages/openmrs/src/http.js
packages/openmrs/test/index.test.js

`post`  `remove` and `get` helpers for HTTP
Fixes #
Added  wrappers, with tests and documentation, for http.get(), http.post() and http.remove.
know!):

Openmrs extra http wrappers

---

packages/googlesheets/CHANGELOG.md
packages/googlesheets/package.json
packages/googlesheets/src/Adaptor.js
packages/googlesheets/test/index.js

See https://github.com/OpenFn/adaptors/pull/927

Release: googlesheets

---

.changeset/cuddly-hairs-beam.md
packages/ghana-bdr/CHANGELOG.md
packages/ghana-bdr/ast.json
packages/ghana-bdr/package.json
packages/ghana-bdr/src/Adaptor.js
packages/ghana-nia/CHANGELOG.md
packages/ghana-nia/ast.json
packages/ghana-nia/package.json
packages/ghana-nia/src/Adaptor.js
pnpm-lock.yaml

This PR swaps examples that were in the wrong place.
know!):

Swap BDR and NIA examples

---

.changeset/cool-actors-argue.md
.changeset/long-parents-fly.md
.changeset/strong-apples-stare.md
packages/odoo/CHANGELOG.md
packages/odoo/package.json

Merge to main with two `odoo` changes
Fixes #
know!):

odoo: merge `odoo` changes to main

---

.changeset/curly-glasses-reply.md
packages/chatgpt/CHANGELOG.md
packages/chatgpt/package.json
packages/claude/CHANGELOG.md
packages/claude/package.json

Update examples in AI adaptors to be more relevant

---

packages/salesforce/test/integration.js

Add integration test for `bulkQuery`
Fixes #1029
know!):
- NA: Is there a changeset associated with this PR? Should there be? Note that

Add `bulkQuery` integration test

---

packages/fhir-4/CHANGELOG.md
packages/fhir-4/package.json

The common dependency in fhir-4 is wrong, which is causing some problems in production

Fhir 4 deps

---

.changeset/nice-hairs-design.md
packages/satusehat/CHANGELOG.md
packages/satusehat/package.json
packages/satusehat/src/Adaptor.js

Export `util.uuid` from common 
Fixes #1112
know!):

satusehat: export `util.uuid` from common

---

.changeset/six-clocks-know.md
packages/mpesa/configuration-schema.json

Add a high-level, single-sentence summary of what this PR changes.
Fixes #1148
know!):

Fix m pesa configuration schema

---

.changeset/chilled-pumas-rest.md
packages/gmail/README.md
packages/gmail/ast.json
packages/gmail/package.json
packages/gmail/src/Adaptor.js
packages/gmail/src/Utils.js
pnpm-lock.yaml

Added support for sending messages. Upgraded zip library to support creating archives as well as reading archives.
know!):

Adding Gmail send functionality to Gmail Adaptor

---

tools/build/src/commands/docs.ts

tools: fix an issue where common docs are no longer tracked

---

packages/common/src/http.js

Update the example for `http.post()` in common, add `data` param docs and update url param to reflect the jsdoc
know!):
- NA: Are there any unit tests?

Update `http.post` docs in common

---

packages/gmail/ast.json
packages/inform/ast.json
tools/slack/src/index.js

Change update slack channel

---

.changeset/chilled-days-walk.md
.changeset/wicked-keys-warn.md
packages/openmrs/CHANGELOG.md
packages/openmrs/package.json
packages/openmrs/src/Adaptor.js

Open MRS next

---

.changeset/late-impalas-burn.md
packages/common/src/util/http.js
packages/dhis2/CHANGELOG.md
packages/dhis2/ast.json
packages/dhis2/package.json
packages/dhis2/src/Adaptor.js
packages/dhis2/src/http.js
packages/dhis2/src/tracker.js
tools/build/src/partials/state.hbs

This should fix Hunter's issues with empty bodies where the server does not return a content-length header
know!):

Better empty body handling

---

.changeset/quick-lizards-wink.md
packages/dhis2/CHANGELOG.md
packages/dhis2/package.json
packages/dhis2/src/meta/config.js
packages/dhis2/src/meta/helper.js

Fix `dhis2` metadata `helper` and `config`
Fixes #1268 
know!):

dhis2: fix dhis2 metadata

---

.changeset/lemon-singers-sparkle.md
packages/openhim/ast.json
packages/openhim/src/Adaptor.js
packages/openhim/test/index.js

- Delete `updateClient`
- Rename `registerClient`
- Update task examples
Fixes #1256
know!):

openhim: Delete `updateClient`, rename `registerClient`, and update task examples

---

.changeset/grumpy-pans-retire.md
packages/gmail/CHANGELOG.md
packages/gmail/README.md
packages/gmail/package.json
packages/stripe/CHANGELOG.md

Enhanced documentation in README.md
Fixes #
Old documentation demonstrated access token retrieval using 3rd party application Postman.
New documentation is demonstrating access token retrieval using Google Developers OAuth playground which is easier and more intuitive.
know!):

gmail: enhanced documentation

---

.changeset/clever-pans-check.md
packages/common/ast.json
packages/common/src/Adaptor.js

Update `fnIf` function docs
Fixes #651 
know!):

 common: Update `fnIf` function docs
