OpenFn/adaptors

.changeset/hot-tomatoes-poke.md
.changeset/wet-swans-speak.md
packages/_template/README.md
packages/primero/README.md

Remove `travis` build status url in readme for `_template` and `primero`

Remove `travis` build url in readme

---

.github/workflows/ci.yaml
packages/common/package.json
packages/common/src/index.js

So we have a problem in how exports are defined in `index.js`, and this is breaking ESM style imports.
This fixes the second part of #88, but not the first.
The problem is that the index.js was exporting a default object and a named export called Adaptor. When you try and do `import { fn } from 'common'` the import fails because it us looking for a name export called `fn` (which doesn't exist), rather than deconstructing the default export.
if you look at the built ESM file in dist, the export structure is a mess. I've been aware of this for a long time, and it's bugged me, but only this afternoon have I managed to understand what's actually happening.
I also agree that we should remove the `main` key  from package json and instead use conditional `exports` to support CJS and ESM - that …

Fix module exports

---

.changeset/tidy-paws-hide.md
package.json
packages/asana/package.json
packages/beyonic/package.json
packages/commcare/package.json
packages/common/package.json
packages/dhis2/package.json
packages/fhir/package.json
packages/googlesheets/package.json
packages/http/package.json
packages/kobotoolbox/package.json
packages/mssql/package.json
packages/ocl/package.json
packages/postgresql/package.json
packages/primero/package.json
packages/salesforce/package.json
packages/sftp/package.json
packages/template/package.json
pnpm-lock.yaml
tools/import-tests/package-lock.json
tools/import-tests/package.json
tools/import-tests/test/import-cjs.js
tools/import-tests/test/import-esm.mjs
tools/import-tests/test/import-json-cjs.js
tools/import-tests/test/import-json-esm.mjs
tools/migrate/package.json
tools/migrate/src/cli.ts
tools/migrate/src/update-package.ts

This PR adds `package.json` as an exported path from all packages.
The migration utility has been updated. I've also added a few unit tests against the builds, just to ensure the package structures are OK. I actually implemented against these tests, if you run them against `main` they should fail.
Also, now we can do `pnpm migrate all`, so that's nice.
Final note - kobotoolbox tests were failing? Fixed now.
Fixes #126 and #116

Fix exports again

---

packages/kobotoolbox/package.json
pnpm-lock.yaml
tools/build/src/commands/ast.ts
tools/build/src/commands/dts.ts
tools/migrate/src/update-package.ts

This PR fixes two issues
1) kobotoolbox is failing to build docs because it doesn't declare a devDependency on simple-ast
2) The docs build will succeed in CI even if the actual build fails and errors are thrown #131
To prove that 2) is fixed, take a look at [this CI run](https://github.com/OpenFn/adaptors/actions/runs/3427846423/jobs/5711343050) for [4467ac6](https://github.com/OpenFn/adaptors/pull/132/commits/4467ac646588f353ecb4e535bfc89d29721be762). You'll see that the build has failed because of an error in kobotoolbox.
The fixes are:
1) Reject the docs promise if there's an error
2) Update the migration util to ensure simple-ast is declared as a dev dependency
3) Update the kobotoolbox dependencies
4) Suppress confusing output of the DTS build step (I'll probably regret this one day …

Fail build if docs build fails (and finally fix kobotoolbox)

---

.changeset/bright-panthers-attack.md
packages/kobotoolbox/src/Adaptor.js
packages/kobotoolbox/test/index.js

I added a `getDeploymentInfo` function which is available on version 2 of [kobotoolbox API](https://kf.kobotoolbox.org/api/v2/assets/)
The function retrieves information about the existing deployment if any.

`kobotoolbox` Add `getDeploymentInfo` helper function

---

packages/dhis2/package.json
packages/dhis2/src/index.js
packages/dhis2/src/index.ts
packages/dhis2/src/types.ts
packages/dhis2/test/metadata/lookup.test.js
packages/dhis2/tsconfig.json
pnpm-lock.yaml
tools/parse-jsdoc/package.json
tools/parse-jsdoc/src/extract-lookups.ts
tools/parse-jsdoc/src/parse-operations.ts
tools/parse-jsdoc/src/parse-ts.ts
tools/parse-jsdoc/test/extract-lookups.test.ts
tools/parse-jsdoc/test/fixtures/types.ts
tools/parse-jsdoc/test/parse-operations.test.ts
tools/parse-jsdoc/test/parse-ts.test.ts
tools/parse-jsdoc/tsconfig.parser.json
tools/parse-jsdoc/tsconfig.test.json

So we have a problem in #196 that we can't unit test magic lookups define in typescript files (ie, all the interesting stuff in dhis2).
This is pretty bad for devx because the model of being able to unit test directly against the jsdoc is gonna be really improtant.
This PR uses `typedoc` to parse `index.ts` and pull out any jsdoc annotations on object interfaces.
It basically works - there's a working unit test! - but I'm having some major drama in finding a config that works across all packages (including tools). Not going to document this in much detail just yet.
Basically when I call typedoc I want to pass in a tsconfig directly. But it stubbornly only accept a path to a tsconfig, which makes it hard to dynamically alter a config to suit a different package. There will be a solution …

Use typedoc for magic lookup unit tests

---

.changeset/lovely-doors-joke.md
packages/salesforce/package.json
pnpm-lock.yaml

Salesforce 3 incorrectly has a dependency on internal tooling `parse-jsdoc`. This is a magic function thing.
This PR reduces it to a dev dependency which means it should work in prod.
I've checked dhis2, which also has magic, and that appears to be fine.
Suggest we release straight from this branch, then merge.

Fix salesforce 3

---

.github/workflows/docs.sh

The docs build command `pnpm -r build docs` was broken due to introduced changes. I have updated the command to `pnpm build:adaptors docs` which will build docs for all adaptors 
closes #219 

update adaptors docs build command

---

.changeset/great-islands-prove.md
package.json
packages/dhis2/package.json
packages/salesforce/package.json
pnpm-lock.yaml

The previous fix to #226 did not work.
`salesforce` and `dhis2` have dependencies on two new internal tools for magic functions: `parse-jsdoc` and `metadata`. These are unpublished packages.
Even though they are declared as devDependencies, npm will throw an error during `install omit=dev` because these packages are not published to npmjs.org.
This is annoying.
But, this is actually really cool.
Instead of declaring internal dev dependencies on the package, we can declare them on the monorepo root.
Now all packages will have visibility over the internal tooling packages without having to add them as an explicit dependency.
Big fan.
We should do this for all adaptors going forward. I don't know whether we should do it all in one go or do it per-package when we need to.
It's not critical …

Better dev dependencies

---

packages/salesforce/test/metadata/metadata.test.js

Some salesforce metadata tests are failing intermittently.
Since the tests run on the same fixture data, I can only think that the fails occur because the array ordering comes out differently.
So I've made the tests more robust by not relying on array order - which can only be an improvement, even if the actual issue isn't resolved.
@mtuchi this doesn't address the fails in your loom video, but I still think that's an install issue(the `jsonpath` module is not installed).
It looks OK on my machine :tm:  but I'd appreciate some more QA. I'll re-run CI a few times.
#237

Salesforce: stabilise metadata tests

---

.changeset/silent-pugs-raise.md
packages/sftp/src/Adaptor.js

Incase of error, `console.log` instead of throw so that the workflow doesn't stop and we get to see the error which makes debugging easy 
Change `throw e` to `console.log(e)`

`sftp` error handling 

---

packages/sftp/src/Adaptor.js

This PR branches off `sftp-improvements`. It uses broadly the same strategy but writes the sftp client to  a variable, rather than state, so it's no longer a breaking change.
I don't really like this approach  - it'll break if the adaptor is somehow loaded twice into an environment. But it'll work in platform and cli, doens't break anything, and fixes the connection problem.
First step is to run some basic QA

Sftp: don't write the client to state

---

.changeset/fuzzy-bobcats-invite.md
packages/openmrs/ast.json
packages/openmrs/src/Adaptor.js
packages/openmrs/src/Utils.js

Add support for `upsert`, `update` & `create` in `OpenMRS` adaptor. & Add `callback` support and improve examples for 
Reference any related issues here. #263 

`OpenMRS` add support for `upsert`, `update` & `create`

---

packages/common/build.config.js
packages/common/package.json
packages/common/src/util.js
packages/common/test/util.test.js
packages/template/src/Adaptor.js
tools/build/src/commands/src.ts

I've added:
1) A new `@openfn/common/util` package which exposes utility functions (designed for other adaptors for now, but we could expose this from common for job code)
2) A new `expandReferences` utility like this:
```
const [_resource, _data] = expandReferences(state, resource, data); 
```
It is just an experiment, but actually I think this can be merged to main very quickly.
The new `expandReferences` function is designed to resolve multiple references in a single line, with a cleaner syntax. It's clean, safe, performant and elegant for every operation factory to call this immediately.
At the time of writing, expandReferences does NOT support the `skip` functionality. That probably requires a `expandReferencesWithSkip(state, skipfn, ...args)` function.
It is up to the adaptor author …

New expandReferences API

---

.changeset/large-monkeys-protect.md
packages/common/src/util.js
packages/common/test/util.test.js
packages/dynamics/configuration-schema.json
packages/dynamics/src/Adaptor.js
packages/facebook/configuration-schema.json
packages/facebook/src/Adaptor.js
packages/facebook/test/index.js
packages/googlehealthcare/configuration-schema.json
packages/googlehealthcare/src/Adaptor.js
packages/googlehealthcare/test/Adaptor.test.js
packages/googlesheets/configuration-schema.json
packages/googlesheets/src/Adaptor.js
packages/googlesheets/test/index.js
packages/msgraph/configuration-schema.json

@josephjclark , this is a bit of a compromise, but as I started to change `accessToken` to `access_token` all over so many Javascript files, I realized that what we actually want is to accept standard JSON credentials (which we now do, see configuration-schemas) and then convert them in a standard way to some JavaScript-sensible configuration.
This is a much lighter change, will handle both snakes and camels, and provides us with an interface for further OAuth2 credential-to-adaptor-auth magic if we need it.
There is a bunch of formatting that got applied (prettier must not have been run on these files before) but the change that's indicative of all this stuff is here: https://github.com/OpenFn/adaptors/pull/298/files#diff-a5033e85ba9e830835a40e0ced8f110c61ba2c8640e42c8c88287932cf542f68R30 …

Normalize access token

---

.changeset/many-moons-turn.md
.changeset/odd-geese-joke.md
.changeset/yellow-pets-march.md
packages/bigquery/ast.json
packages/bigquery/src/Adaptor.js
packages/common/ast.json
packages/common/src/Adaptor.js
packages/common/test/index.js
packages/http/ast.json
packages/http/src/Adaptor.js
packages/http/test/index.js
packages/sftp/ast.json

Use  `common` `parseCsv` in `http` and `bigquery`

Extend `parseCsv` to `http` and `bigquery`

---

.changeset/happy-days-sin.md
packages/googlehealthcare/ast.json
packages/googlehealthcare/configuration-schema.json
packages/googlehealthcare/src/Adaptor.js
packages/googlehealthcare/src/Utils.js
packages/googlehealthcare/test/Adaptor.test.js

Add a title and description in properties of `googlehealthcare` configuration schema
This should fix the empty input box when adding Google Healthcare credentials on Lighting 

Update `googlehealthcare` configuration-schema

---

README.md

Add a high-level, single-sentence summary of what this PR changes.
Reference any related issues here.

Expand adaptor docs

---

.changeset/fresh-comics-talk.md
packages/msgraph/src/Adaptor.js
packages/msgraph/test/Adaptor.test.js

When catching an error on `execute()` i added a cleanup step then throw an error. Before that we were doing cleanup without throwing an error which made job code to pass even if there is a `throw new Error()` in that job code 
Ref #319 

`msgraph` cleanup state before throw

---

.changeset/smooth-countries-move.md
packages/mailchimp/README.md
packages/mailchimp/src/Adaptor.js
packages/mailchimp/src/Utils.js
packages/mailchimp/test/index.js

`mailchimp` new functions

---

.changeset/happy-worms-shake.md
.github/workflows/ci.yaml
packages/medicmobile/package.json
pnpm-lock.yaml

This PR bumps the `query-string` dependency of `medicmobile`.
Although `query-string` goes up several major versions, really its just because of keeping track with node versions. Looking over the history I don't think there's anything for us to worry about - we just get better quality and safer query string parsing.
Note: I originally wanted to just bump the affected library `encode-uri-component` - but adding the override didn't seem to work in my test project :thinking:  Looking over the `query-string` changes I'm sure this is a safe alternative.
This closes #328 and allows us to close the related security advisory.

Fix medicmobile

---

.github/workflows/ci.yaml
pnpm-lock.yaml

This PR updates the lockfile version to v6 (pnpm v 8.6.9)
It also ensures that CI runs off the same version, pnpm 8.6.9

bump pnpm version

---

.changeset/red-glasses-switch.md
packages/mailgun/package.json
packages/mailgun/src/Adaptor.js
pnpm-lock.yaml

Update mailgun.js so that we can resolve security vulnerabilities.
This PR removes the deprecated `mailgun-js` package and replaces it with the latest `mailgun.js`.
This resolves security issues but does not change the user-facing API of the library.
Closes #324

Mailgun: update to mailgun.js

---

packages/mongodb/CHANGELOG.md
packages/mongodb/configuration-schema.json
packages/mongodb/src/Adaptor.js
packages/mongodb/test/index.js

Fixes OpenFn/adaptors#353
Fixes JSON schema verification for mongodb clusterUrl configuration 
In packages/mongodb/src/Adaptor.js, the connect() function constructs the URI for the MongoDB cluster as follows:
```
const uri = `mongodb+srv://${encodeURIComponent(
username
)}:${encodeURIComponent(
password
)}@${clusterUrl}/test?retryWrites=true&w=majority`;
```
The adaptor expects the `clusterUrl` configuration property be provided as a hostname and not a full URI, but the current JSON schema specifies the format of this property as `uri`, which fails validation when providing a normal hostname. This PR changes the JSON schema to verify this property as the correct format (`hostname`, not `uri`). The PR also renames the property and fixes all references to the property in the adaptor and …

Update configuration schema for MongoDB adaptor. 

---

.changeset/popular-taxis-shave.md
packages/mailchimp/ast.json
packages/mailchimp/src/Adaptor.js
packages/mailchimp/test/index.js

**Add `chunk` from common**
> Most of Mailchimp operations have a limitation of `500` records per request, having access to `chunk` helper function simplify job code and make it easy to chunk your data before making a request to Mailchimp 
**Improved error message**
> The error response returned did not have enough details to help you debug your job code, This improvement will give you more details about the Mailchimp error
**Return state in request**
> The return for `request()` helper did not include `state`. This improvement return state when use `request()` function
Fixes #365 

`mailchimp` improvements

---

README.md
packages/mailchimp/src/Adaptor.js
tools/build/src/cli.ts
tools/build/src/commands/ast.ts
tools/build/src/commands/src.ts
tools/build/src/pipeline.ts

This PR add a watch mode to build.
It only works for the `src` build (it doesn't work for dts, docs or ast). This is probably the most important as it's what you need when testing with the CLI.
To watch changes in salesforce, you can do:
```
pnpm -C package/salesforce build --watch
```
Or
```
cd packages/salesforce
pnpm build --watch
```
In watch mode, saving a file in `src` will cause the bundle in `dist` to be immediately regenerated.
Note that this won't detect changes in `common` if you're working on another adaptor - if working on common stuff you might want to set up two watches.
Closes #367

Watch mode

---

packages/postgresql/configuration-schema.json

Fixes #381 
This commit removes the URI formatting requirement so we can use IP addresses for the postgres adaptor.
@mtuchi , is there a way to allow _either_ a URI or an IP address? maybe `hostname`? Note that right now the only example on `main` fails on Lightning, since it doesn't start with `http(s):`
https://opis.io/json-schema/2.x/formats.html#hostname
How would this be handled by Lightning when it does form validation?

Allow IPs for postgres host

---

.changeset/chatty-tips-shop.md
packages/kobotoolbox/configuration-schema.json

This PR addresses[ this issue](https://github.com/OpenFn/Lightning/issues/1089). The root cause of this bug stems from the mismatch between the JSON-schema definition and the UI behavior. Specifically, while the schema defined an enum for a particular field, the app used an input field for user entry instead of a select box.
- Removed the Enum Definition - The enum in the schema has been replaced with a type definition of string. This offers flexibility for the app's input mechanism without restricting to predefined values.
- Added Placeholder - A placeholder has been introduced to guide users on the expected value for this field.
Fixes [#1089](https://github.com/OpenFn/Lightning/issues/1089)
dev only …

Remove enum from Kobotoolbox configuration-schema.json

---

.changeset/nine-pugs-collect.md
packages/sftp/ast.json
packages/sftp/src/Adaptor.js

Add a filter `option` in `list()` function. The new function signature `list(dirPath, filter, callback)`
Related issue https://github.com/OpenFn/women-for-women/issues/126

add filter in list function

---

packages/salesforce/CHANGELOG.md
packages/salesforce/ast.json
packages/salesforce/package.json
packages/salesforce/src/Adaptor.js
pnpm-lock.yaml

Add a `bulk2` function that creates and execute a bulk job using Salesforce Bulk API v2. Also updated the `bulkQuery` function to use jsforce `bulk2.query` function
I have updated the `jsforce` dependency to `v2.0.0-beta.28`. This version supports Salesforce Bulk V2.
For the implementation of `bulk2` behind the scene we are using [bulk2.loadAndWaitForResult](https://jsforce.github.io/jsforce/classes/api_bulk.BulkV2.html#loadAndWaitForResults) function and for `bulkQuery` we are using [bulk2.query()](https://jsforce.github.io/jsforce/classes/api_bulk.BulkV2.html#query)
Ref #407 

`salesforce` BulkV2 support

---

.changeset/unlucky-cobras-matter.md
packages/dhis2/src/Adaptor.js
packages/dhis2/src/Utils.js

remove Class Log and replaced
- `Log.success` with `console.log`
- `Log.warn` with `console.warn`
- `Log.error` with `console.error`

`dhis2` remove `Class Log`

---

.changeset/gold-cars-applaud.md
packages/sftp/src/Adaptor.js
packages/sftp/src/Utils.js

handle error on `commonExecute` and improve operation time logs
Ref #421 

`sftp` disconnect on error

---

.changeset/angry-suns-give.md
packages/sftp/src/Adaptor.js

This is a fix for `sftp` adaptor that was missed on #422. When an error happens, The adaptor will disconnect then throw the error instead of `console.error(error)`. This makes sure that we get `Exit Code 1` on platform-app
Ref #421

`sftp` disconnect then throw

---

.changeset/brave-carrots-suffer.md
packages/http/CHANGELOG.md
packages/http/package.json
packages/http/src/Adaptor.js

Returned only `{ method, path, host, protocol }` for `response.request`. which lighten the final state  
Reference #432 

`http` lighten `response.request`

---

.changeset/slow-crabs-lay.md
packages/salesforce/CHANGELOG.md
packages/salesforce/ast.json
packages/salesforce/package.json
packages/salesforce/src/Adaptor.js
packages/salesforce/test/Adaptor.test.js
pnpm-lock.yaml

Add `toUTF8` function, This function transliterates unicode characters to their best ASCII representation
Ref #442 

Add `toUTF8` function in `salesforce`

---

.changeset/perfect-crews-love.md
packages/http/CHANGELOG.md
packages/http/package.json
packages/http/src/Adaptor.js

Add `expandReferences` on `parseXML` `body` argument 
Using the old `expandReferences` from `'@openfn/language-common'` in `parseXML` `body` param

Add `expandReferences` on `parseXML`

---

.changeset/sour-shirts-wonder.md
packages/godata/CHANGELOG.md
packages/godata/configuration-schema.json
packages/godata/package.json

Make Godata email field be in read and write mode for Lightning
This PR proposes to update the `godata/configuration-schema.json` to make the email field in read and write mode for Lightning
Fixes [#1545](https://github.com/OpenFn/Lightning/issues/1545)

Make GoData Adaptor Email Field Be In Read & Write Mode

---

.changeset/angry-grapes-cover.md
packages/mailchimp/CHANGELOG.md
packages/mailchimp/configuration-schema.json
packages/mailchimp/package.json
packages/salesforce/CHANGELOG.md
packages/salesforce/configuration-schema.json
packages/salesforce/package.json

This PR ships code that removes the regex patterns that were used for validation in the mailchimp and salesforce adaptors configuration-schema.json file. We are removing those because:
- they were introducing severe bugs to Lightning migrations.
- the regex patterns seems to not match as expected
We need to discuss whether we need those patterns, in that case make sure we have the right ones
Fixes #451 

Remove Regex Patterns In Configuration Schemas

---

.changeset/four-coats-rhyme.md
packages/salesforce/configuration-schema.json
packages/salesforce/oauth-configuration-schema.json
packages/salesforce/src/Adaptor.js

Add support for `OAuth2` in salesforce adaptor
Improved the `createConnection` function to handle both `accessToken` connection and Basic Auth connection. I have created two functions [`createBasicAuthConnection` and `createAccessTokenConnection`] that gets called in `createConnection` depending on configuration-schema. I have also created another configuration-schema for `OAuth` which requires `other_params.instance_url` and `access_token`. 
Also in `configuration-schema` I have removed the `securityToken` from `required` property since it's an optional value

`OAuth2` support in salesforce

---

.github/workflows/docs.yaml

This PR ensures that the docs action only runs AFTER the publish action. This guarantees we don't build docs for unreleased software, which suddenly became a risk when I added automated releases.
I don't know how to test this. I'm going to keep it open to the next release so that it's visible. I don't want to merge it, forget it, then waste an hour trying to work out why the docs site doesn't build.
Closes #467

Only run Docs after Publish

---

.changeset/itchy-spiders-scream.md
packages/salesforce/CHANGELOG.md
packages/salesforce/oauth-configuration-schema.json
packages/salesforce/package.json
packages/salesforce/src/Adaptor.js

Update `instance_url` in `oauth-configration-schema.json` to be in the root of configuration schema for Salesforce OAuth. And update `createAccessTokenConnection` in `adaptors.js`
Ref #472 

Put `instance_url` at the root of configuration schema for Salesforce OAuth

---

.changeset/healthy-countries-dream.md
packages/mailgun/CHANGELOG.md
packages/mailgun/configuration-schema.json
packages/mailgun/package.json

Update configuration schema for `mailgun` adaptor
Using the adaptor `mailgun` adaptor you only need the `hostname` in you're credentials. This PR changes the `Domain URL` to `Domain Name` and update the format from `uri` to `hostname`.  

Update `mailgun` configuration-schema

---

.github/workflows/docs.sh
pnpm-lock.yaml
tools/build/package.json
tools/build/src/commands/docs.ts
tools/build/src/partials/members.hbs
tools/build/src/util/docs-template.backup.hbs
tools/build/src/util/docs-template.hbs
tools/build/src/util/extract-exports.ts
tools/build/src/util/hbs-helpers.js

This PR adds a list of common exports to the docs markdown generated by the build.
The task here is to get the list of exports from common for each adaptor and add them to the page somewhere.
jsdoc basically can't do it. It seems to have no means to list documentation for export aliases from another module. You can document the export statement and jsdoc will respect it. I considered adding build tooling to generate docs for each export.
But why? The result is a long list of funcitons and when looking at the actual docs, you can't tell the main adaptor functions from the common ones. I mean common mostly introduces a load of noise to the documentation - the most valuable docs are the ones native to this adaptor.
So I took a different approach. 
- Using `acorn`, parse the JS files for the …

List common exports in all docs

---

.changeset/green-lions-pump.md
packages/googlesheets/CHANGELOG.md
packages/googlesheets/ast.json
packages/googlesheets/package.json
packages/googlesheets/src/Adaptor.js

#495 PR added support for callback in googlesheets functions. But i forgotten to add the jsdoc for callback option. This PR amend those changes for each function that supports callback in googlesheets  

Add `callback` in `gsheets` docs 

---

.changeset/poor-elephants-serve.md
packages/mssql/CHANGELOG.md
packages/mssql/ast.json
packages/mssql/configuration-schema.json
packages/mssql/package.json
packages/mssql/src/Adaptor.js

Improved the `configuration-schema` to support extra properties. All properties have default values and can be change if need when setting up a credential for `mssql`
- Set the following options in configuration-schema with default values 
```
- encrypt = true
- rowCollectionOnRequestCompletion = true
- trustServerCertificate = true
- port = 1433
```
- I have also remove un-used import of `url`
- I have update the configuration-schema for `server` to use one of `hostname, uri, on ipv4` #511 
- Import `cursor()` from `language-common`

`mssql` update schema and expose cursor

---

packages/http/CHANGELOG.md
packages/http/configuration-schema.json
packages/http/package.json
packages/http/src/Utils.js
packages/http/test/index.js

We may have stumbled on an issue where if state.configuration has a username and password,  AND the user passes their own Authorization header, we overwrite their header with own own basic auth.
This feels wrong: if the user has defined their own authorization header, we should use it regardless of what exists on state.
Fixes #539

http: don't override the auth header

---

packages/dhis2/CHANGELOG.md
packages/dhis2/package.json
packages/dhis2/src/meta/config.js
packages/dhis2/src/meta/helper.js
packages/dhis2/src/meta/metadata.js
packages/dhis2/test/fixtures/getAttributes.json
tools/metadata/package.json

dhis2 metadata is loading attributes from the wrong endpoint.
We should be loading trackedEntityAttributes, not attributes.
Maybe one day we need both but for now, this just provides more useful metadata.
Closes #557

dhis2: fix attribute metadata

---

packages/commcare/package.json
packages/commcare/src/Adaptor.js
packages/commcare/src/Utils.js
packages/commcare/test/index.js
packages/commcare/test/integrations/JobExample.js
pnpm-lock.yaml

Switch `commcare` adaptor implementation to use `fetch` for all http calls
Currently the `commcare` module utilizes superagent and `language-http` to handle its requests.  Our aim was to switch the implementation with normal fetch.
Fixes #414

Commcare: replace superagent with common http helpers

---

.changeset/small-pots-wave.md
packages/commcare/src/Adaptor.js
packages/commcare/src/Utils.js

Creating a single auth systems that will check the `config` and authorize depending on the availability of an api key or password
The current implementation of auth is to allow for both basic and API key at the same time and we needed to make it better by only allowing one type of auth depending on the `config`. 
#554 

Commcare: standardize auth

---

packages/commcare/package.json
packages/commcare/src/Adaptor.js
packages/commcare/src/Utils.js
packages/commcare/test/index.js
packages/common/src/util/http.js
pnpm-lock.yaml

Fixes to the `submitXls` function
Since switching from axios to undici, the submitXls function has failed. There are many reasons for this:
* commcare uses `form-data`, but it shouldn't. Using the `form-data` object made the common helper not recognise the form data and encode the payload into a string
* It turns out that when sending form data, we explicitly must not pass a header value. Unidici will work it out with the boundary encoding. So there's some fixes around this
I've also added a unit test for submitxls. It's not very good coverage but it's a start!
There is a tiny change to common because the test agent was calling out to the internet and hitting actual commcare servers. I thought we'd disabled that - but I've done it now.
No changesets are required for this PR

Commcare: fix xlsx

---

.changeset/rare-toys-clap.md
packages/fhir/CHANGELOG.md
packages/fhir/ast.json
packages/fhir/configuration-schema.json
packages/fhir/package.json
packages/fhir/src/Adaptor.js

Update required properties in configuration schema and improved the `create()` example
The required properties for `fhir` adaptor were wrong, `resource` property doesn't exist and the other properties were not required. This PR update the required properties list to contain only the required items

`fhir` Update configuratio-schema

---

.changeset/strong-items-lay.md
.changeset/young-bees-wait.md
packages/commcare/ast.json
packages/commcare/package.json
packages/commcare/src/Adaptor.js
packages/commcare/src/Utils.js
packages/commcare/test/index.js
packages/common/src/util/http.js
pnpm-lock.yaml

Creating a `get` function to be used to fetch data from `commcare`
Commcare does not have a get handler that can be used to fetch various data. The `get` function will be used to fetch data such as `case, forms`.
#528 

Commcare: Get function handler

---

.changeset/proud-impalas-act.md
packages/commcare/src/Adaptor.js
packages/commcare/src/Utils.js
packages/commcare/test/index.js

Creating a generic `post` function for commcare
We currently have `submit` and `submitxls` which cater to submitting form-data and xls data. However, we do not have a generic post that can allow to send JSON data. 
#570 

Commcare: Implement generic `post` function

---

.changeset/mighty-eyes-guess.md
packages/salesforce/CHANGELOG.md
packages/salesforce/ast.json
packages/salesforce/package.json
packages/salesforce/src/Adaptor.js

`bulkQuery` uses [Bulk API 2.0 Query](https://developer.salesforce.com/docs/atlas.en-us.api_asynch.meta/api_asynch/query_create_job.htm) which available in API version 47.0 and later. I have updated the default `apiVersion` to `47.0`, If apiVersion is not set.
- Set the default apiVersion to `47.0` 
- Throw an error in `bulkQuery` if apiVersion is less than `47.0`
- Update `bulkQuery` docs with the link to `Bulk API 2.0 Query`
Ref #577 

`salesforce` Update default `apiVersion`

---

packages/http/CHANGELOG.md
packages/http/configuration-schema.json
packages/http/package.json
packages/http/src/Utils.js
packages/http/test/index.js

This PR reads the `token` from the config object and adds it to an `Authorization: Bearer ${token}` header.
I think this is all that's needed? It should work with oath and I think most api key-style APIs. I don't know how much variance there is in the pattern, maybe we can add more flexibility later if needed.
Note that users can provide their own Authorization header in the request, so even if this doesn't work in all cases, there's an easy work around.
Closes #581

http: automatically add bearer tokens to a request

---

packages/salesforce/CHANGELOG.md
packages/salesforce/package.json
packages/salesforce/src/Adaptor.js

It's theoretically possible that `any-ascii` has not loaded before `toUTF8` is called.
This seems vanishingly unlikely since we have to call out to the salesforce server before we start executing. Can we really handshake with Salesforce quicker than we can load a Javascript Module? 
But Mutchi is seeing an runtime error  where `anyAscii is not a function`. If I locally disable the salesforce connection code and just call `toUTF`, then it fails the same way. So it feels like somehow the module loader is losing the race :shrug: 
Anyway this is a more robust solution and I wish I'd thought of this earlier.

salesforce: Ensure anyscii is loaded before executing

---

packages/salesforce/CHANGELOG.md
packages/salesforce/package.json
packages/salesforce/src/Adaptor.js
packages/salesforce/test/Adaptor.test.js

The previous fix to UTF8, which introduced loadAnyAscii, didn't quite work.
This PR basically just wraps that function in a function, which ensures that `execute` properly waits for the module to load.
This now works against a local worker, so I'm more confidence it'll work in production.
Also note that to support this fix I've improved the unit tests on `toUTF8`. They now use `execute`, which forces the dynamic module load of `any-ascii`

Salesforce: second fix to UTF8

---

packages/cartodb/package.json

Cartodb has been building as `rapidpro` since migrating into the monorepo last year.
Closes #616 
No changeset and no version bump needed

Fix cartodb

---

.github/workflows/prerelease.yaml

To get the `run_workflow` trigger to work, we need it on main. Annoying.

Add stub script to main

---

README.md
package.json
pnpm-lock.yaml
tools/build/package.json
tools/build/src/cli.ts
tools/build/src/commands/docs.ts

A quick PR to add `--watch` support on docs builds (ie, generate docs md files for adaptos) and the main docs.json build

Watch docs

---

.changeset/strange-trainers-promise.md
packages/odk/CHANGELOG.md
packages/odk/ast.json
packages/odk/configuration-schema.json
packages/odk/package.json
packages/odk/src/Adaptor.js
packages/odk/src/Utils.js
packages/odk/test/Adaptor.test.js

- ODK uses `email`, not `username`. This changes the config schema so it matches what ODK wants and what their documentation provides. (https://docs.getodk.org/central-api-authentication/)
- By manually concatenating the `baseUrl` and the `path` in the adaptor, rather than relying on `commonRequest` to do so, we lost the ability to handle `/` addition/omission. We don't want users to have to figure out if they should or shouldn't put `/` in various places.
- This adds a log to explain that authentication failed.
- This removes the try/catch so that users can see the helpful error message returned by `commonRequest`

Small fixes on ODK

---

.changeset/funny-planes-switch.md
packages/satusehat/CHANGELOG.md
packages/satusehat/package.json
packages/satusehat/src/Adaptor.js

Adding error logs to `satusehat`
`satusehat` errors are not correctly displayed therefore a temporary log has been added to display the errors before the CLI error log is fixed.
#655 

fix:add error logs

---

.changeset/shy-vans-study.md
packages/commcare/CHANGELOG.md
packages/commcare/ast.json
packages/commcare/package.json
packages/commcare/src/Adaptor.js
packages/commcare/test/index.js
pnpm-lock.yaml

Implement pagination on commcare`get`
A manual implementation of pagination of data fetched from commcare. Users can override the default pagination when they pass in `offset` and/or `limit` 
#569 

commcare: Implement pagination on commcare's get request

---

.changeset/famous-sloths-talk.md
.changeset/twenty-lemons-fail.md
.github/workflows/publish.yaml
packages/common/src/util/http.js
packages/common/test/util/http.test.js
packages/surveycto/CHANGELOG.md
packages/surveycto/package.json
packages/surveycto/src/Adaptor.js
packages/surveycto/src/Utils.js
packages/surveycto/test/index.js

SurveyCTO 2.2.1 has started throwing an error on `fetchSubmissions`:
```
TypeError: Cannot read properties of undefined (reading 'toString')
```
Turns out this is a bug introduced in the recent patch.
I've snuck in a little tweak here to run `pnpm chaneset tag && git push --tags` after publish.
I have had trouble getting this to work in the past, but let's see if it work this time :crossed_fingers:  We'll just have to see.
I should have clocked that this would be problematic, but we didn't have enough tests in the adaptor (and I didn't add them) so it got by me.
We've been using a new pattern of `path.join(a,c,b)` for safer URL assembly. It works great on paths - but when surveyCTO does it, it builds a whole URL, starting with `https://`. And when nodepath sees `//` it strips out the …

Fix survey CTO and automate tags

---

.changeset/moody-cycles-learn.md
packages/commcare/ast.json
packages/commcare/src/Adaptor.js

Revise the Commcare docs to be "best in class"
I am working on a  documentation guide in tandem: https://github.com/OpenFn/adaptors/wiki/Documentation-Guide
* Remove RequestQueries and RequestOptions, linking to CommCare instead
* Improve examples (updated syntax, always a caption, more use-cases)
* Tweak English and phrasing
* State tables
#702

commcare: docs review

---

.changeset/three-items-perform.md
packages/redis/ast.json
packages/redis/src/Adaptor.js
packages/redis/test/Adaptor.test.js

Update scan to `scan` function to scan whole database based on the provided pattern 
Ref: #710 

`redis` update `scan` function 

---

packages/redis/ast.json
packages/redis/src/Adaptor.js
packages/redis/src/Utils.js
packages/redis/test/Adaptor.test.js

Add `jSet(key: string, values: object)` function. 
Ref #709 
**Notes**
changeset is in `release/redis` branch

`redis` add `jSet` function

---

.changeset/ninety-brooms-tickle.md
packages/redis/CHANGELOG.md
packages/redis/configuration-schema.json
packages/redis/package.json

Update `redis`  host type `configuration-schema` to use `string`. This will remove the validation error on lightning when a user is creating the redis credential 

`redis` Update host type configuration-schema

---

.changeset/flat-peas-notice.md
packages/redis/CHANGELOG.md
packages/redis/ast.json
packages/redis/package.json
packages/redis/src/Adaptor.js
packages/redis/test/Adaptor.test.js

Add `mGet()` function in redis adaptor with unit tests.  `mGet()` function is used to get multiple json keys from redis. 
Related #731

`redis` Add `mGet` operation  

---

.changeset/light-forks-arrive.md
packages/openmrs/ast.json
packages/openmrs/src/Adaptor.js

Add `cursor` and `dateFns` in `openmrs` adaptor 

`openmrs` add cursor and dateFns

---

.changeset/thin-icons-change.md
packages/mssql/CHANGELOG.md
packages/mssql/package.json
packages/mssql/src/Adaptor.js

Removed the catch logic on `execute()` function. The catch was using `process.exit(1)` which cause a crash and stop the whole workflow from running. 
- https://github.com/OpenFn/health-partners/issues/24

`mssql` remove process.exit(1)

---

package.json
packages/fhir/ast.json
packages/fhir/build-dts.ts
packages/fhir/package.json
packages/fhir/src/Adaptor.js
packages/fhir/src/Utils.js
packages/fhir/src/Utils.ts
packages/fhir/src/index.ts
packages/fhir/src/types.ts
packages/fhir/test/Adaptor.test.js
packages/fhir/tsconfig.json
pnpm-lock.yaml
test.js
tools/build/src/commands/dts.ts

An experiment to add typescript support to `create`, giving code assist while using that particular function.
This was conceived as a quick alternative to the FHIR Builders issue. But it won't get us very far because each fhir implementation is different and the generic types aren't actually all that useful.
What we really need to be able to auto-generate a fhir adaptor based on a spec, and for the autogenerated mapper to include typings, cross-version mappings, and builders. All the information is there in the spec so it's possible.
Anyway I'm going to keep this open for a little while in case it provides a useful template for something later.
This is left basically in a broken state.
The big problem right now (apart from a hack to shortcut the dts build in fhir) is that the typings …

Add typescript defs to fhir create

---

.changeset/hot-beers-flash.md
packages/commcare/ast.json
packages/commcare/package.json
packages/commcare/src/Adaptor.js
packages/commcare/test/index.js
pnpm-lock.yaml

Implemented a `bulk` upload for allowing to upload and update `lookup-tables` and `case-data`.
Fixes # #751 

feat: implement bulk upload for lookup-tables and case-data

---

.changeset/wicked-masks-buy.md
pnpm-lock.yaml

Update dependencies with security vulnerability detected in `pnpm-lock.yaml` by dependabot. This should closed down a good number of security alerts
Should Fix 👇🏽 
- https://github.com/OpenFn/adaptors/security/dependabot/103
- https://github.com/OpenFn/adaptors/security/dependabot/46
- https://github.com/OpenFn/adaptors/security/dependabot/52
- https://github.com/OpenFn/adaptors/security/dependabot/93
- https://github.com/OpenFn/adaptors/security/dependabot/74
- https://github.com/OpenFn/adaptors/security/dependabot/88
- https://github.com/OpenFn/adaptors/security/dependabot/59 `major version bump`
I have used the recursive option to update all detected packages. `pnpm update dependency -r`
You can read …

Update vulnerable dependencies 

---

.changeset/quiet-plums-clap.md
packages/http/src/Utils.js
packages/http/test/index.js

Add better error when `baseUrl` is not set and the passed url is a relative url.
Fixes #
- #733 
Added an if statement that check if baseUrl is not set and check if the url is not an absolute url. If both conditions are true, I am throwing an error `UNEXPECTED_RELATIVE_URL`. In addition if `baseUrl` is not set and no url is provided, i am throwing `ERROR_NO_URL`

`http` better error when no `baseUrl` and no absolute url

---

packages/kobotoolbox/CHANGELOG.md
packages/kobotoolbox/package.json
packages/progres/CHANGELOG.md
packages/progres/package.json
packages/rapidpro/CHANGELOG.md
packages/rapidpro/package.json
packages/salesforce/CHANGELOG.md
packages/salesforce/package.json
packages/twilio/CHANGELOG.md
packages/twilio/package.json
pnpm-lock.yaml

This PR fixes the final adaptors from #782.
This is the final fix to #781
Now that we've released common 1.15.2 in #784, this PR updates the small number of adaptors with fixed dependencies

Fix  json path for adaptors version locked to common 1.15.1

---

.changeset/cool-news-train.md
packages/mssql/CHANGELOG.md
packages/mssql/package.json
packages/mssql/src/Adaptor.js

Fix typo in changelog and log entire error message 
When the job fail on lightning the logs does not contain any useful information that could help with debugging, See example error message 👇🏽  
```
T Failed step Upsert feedback table on Azure after 2.348s
R/T {
"details": {},
"message": "",
"name": "AdaptorError",
"severity": "fail",
"source": "runtime"
}
R/T Check state.errors.b1de9d3b-ba65-49cf-8fff-147759b09736 for details.
R/T Run complete with status: fail
AdaptorError: unknown
```
This PR makes sure we log the whole error message when we have an error 
Before merging, the reviewer should check …

`mssql` Improve error logs

---

.changeset/lovely-books-help.md
packages/fhir-ndr-et/CHANGELOG.md
packages/fhir-ndr-et/README.md
packages/fhir-ndr-et/package.json

This PR fixes the jembi build so that:
- `pnpm build` does not rebuild the source
- CI builds therefore do not rebuild the source
- Local devs use `build:src` to build the source
Fixes #790 #776
This might even fix #763, if the last build failed to generate typings properly.

fhir-jembi: Fix build

---

.changeset/kind-snails-scream.md
packages/commcare/CHANGELOG.md
packages/commcare/configuration-schema.json
packages/commcare/package.json
packages/commcare/src/Adaptor.js

Update `commcare` documentation with more examples and better formatting
Fixes #775 
Add more examples and update the `commcare` documentation

Commcare: update documentation

---

.changeset/wild-dodos-rush.md
packages/dhis2/CHANGELOG.md
packages/dhis2/README.md
packages/dhis2/package.json
packages/dhis2/src/Adaptor.js
pnpm-lock.yaml

Add warning and update readMe on the API version update
Fixes #754
Nothing has been changed, only a warning has been added when the adaptor loads and the readMe updated with the same warning

dhis2: Implement breaking version warnings

---

packages/collections/CHANGELOG.md
packages/collections/package.json
packages/collections/src/collections.js
packages/collections/src/mock.js
packages/collections/test/Adaptor.test.js

This PR restricts `set()` to upsert 1000 items at a time.
This helps avoid database limits at the database end.
This is a bit of a temporary fix and we will soon add smarter streaming APIs and backend batching.

Collections: restrict set to batches of 1000

---

packages/collections/CHANGELOG.md
packages/collections/package.json
packages/collections/src/collections.js
packages/collections/test/Adaptor.test.js
pnpm-lock.yaml

I forgot an await in the streaming parser, which caused inconsistent issues when streaming data down. 
Fixes #829
I've also removed a little bit of code we don't need.

Collections: patch for streaming JSON

---

.changeset/ten-spiders-return.md
packages/dhis2/CHANGELOG.md
packages/dhis2/package.json
packages/dhis2/src/Adaptor.js
packages/dhis2/test/integration.js

Two fixes for DHIS2:
* Fix an issue resolving the `path` argument to `update`
* Restore Integration tests
Fixes #207
Integration tests should now run locally (but never in CI)
The state of the sandbox may cause failures in future, but they're working at the moment
Thanks to @mtuchi  for help

dhis2: fix integration tests

---

packages/fhir-fr/CHANGELOG.md
packages/fhir-fr/package.json
packages/fhir-fr/src/index.ts
tools/generate-fhir/template/package_json
tools/generate-fhir/template/src/index.ts

The type exports for fhir-fr aren't quite right
This PR updates them for the adaptor itself but also for the template

fhir-fr typings

---

packages/fhir-fr/CHANGELOG.md
packages/fhir-fr/package.json
packages/fhir-fr/types/builders.d.ts
tools/generate-fhir/CHANGELOG.md
tools/generate-fhir/package.json
tools/generate-fhir/src/generate-dts.ts

Another attempt to fix typings in Lightning
After some experiments it looks like the current typings aren't working properly and are only providing a union of all possible types.
Basically we have to change `function patient<T extends Patient_variants>(type: Patient_variants, props: Patient__lookups[T]);;` to `function patient<T extends keyof Patient__lookups>(type: T, props: Patient__lookups[T]);`
This seems to work  way better. Need to release to test against Lightning.
Fixes #844
- [x ] I have not used AI

Fhir type fix again

---

packages/fhir-fr/CHANGELOG.md
packages/fhir-fr/package.json
packages/fhir-fr/src/index.js
packages/fhir-fr/src/index.ts
packages/fhir-fr/types/index.d.ts
packages/fhir-ndr-et/src/index.ts
tools/generate-fhir/CHANGELOG.md
tools/generate-fhir/package.json
tools/generate-fhir/template/src/index.ts

Something strange happened with fhir-fr's index.js and broke the exports.
This is a quick fix. Can't see what went wrong - rebuilding seems to work fine

Fhir fr exports

---

.changeset/sour-doors-dance.md
packages/mssql/package.json
pnpm-lock.yaml

This PR updates the `tedious` dependency from v15.x to 18.x, and includes numerous security fixes.
The only breaking changes I can see are in typescript definitions (which do not affect us) and node version support (dropping support for node versions 14, 16, 19)
I have not updated to the very latest v19, because it only supports node 18.17 or later. That's _probably_ fine for all our past CLI and worker releases but I see no reason to take a risk. 
For the record this repo right now is on 18.17.1.
Closes https://github.com/OpenFn/adaptors/security/dependabot/94

mssql: update tedious

---

.changeset/ten-mayflies-nail.md
packages/salesforce/ast.json
packages/salesforce/src/Adaptor.js
packages/salesforce/test/Adaptor.test.js
tools/parse-jsdoc/jsdoc/jsdoc.conf.json

- Update params documentation and improve examples in salesforce adaptor  
- Add `query` option in `request` function 
Fixes #664 

`salesforce` update function docs 

---

.changeset/good-colts-obey.md
packages/salesforce/ast.json
packages/salesforce/src/Adaptor.js
packages/salesforce/src/util.js
packages/salesforce/test/util.test.js

Add utils helper `validateNoDotKeys` and `flattenData` to help with validation of input data when using `upsert`, `update` or `create` and to transform nested object into a dot notation syntax when using `bulk` operation.
Fixes #556 
When mapping a salesforce data model there is a bit of confusion on when to use the `dot notation` and when not to. Since the best practice when mapping objects is to always use a nested object for relationship, it's important that the adaptor adds a safe check when you forgot and use the `dot notation` to map salesforce relationship. This PR adds two things 
1. A validation step for `upsert`, `update` and `create` function. This is achieved by the new util helper `validateNotDotKeys`
2. A transformer to a dot notation syntax when using `bulk` function. This …

`salesforce` Add helper for validating and format input data

---

.changeset/ninety-paws-own.md
packages/common/ast.json
packages/common/src/Adaptor.js
packages/common/test/index.test.js

Added an 'assert' function to  the common adaptor
Fixes #876
Created an assert function that aborts  execution when it fails. 

Common add assert() function

---

.changeset/light-spiders-move.md
packages/common/src/util/base64.js
packages/common/test/util/index.test.js

Adds functionality to encode and decode JSON objects in the encode and decode util functions
Fixes #794
Added a conditional in the `encode` util to check for objects and stringify them first before encoding them.
Added functionality to `decode` that handles JSON objects and parses them to standard JavaScript objects.

Common util encode should take an object and stringify

---

.changeset/yellow-lions-double.md
packages/commcare/CHANGELOG.md
packages/commcare/package.json
packages/commcare/src/Adaptor.js
packages/commcare/src/Utils.js

Updated the `options` sections in the `request` function to query parameters, and fix the response body when result is undefined.
Fixes #903 
The `options` section in the docs is misleading as the items are passed to the URL, and therefore changed to `params`. When a request is made and the response is an empty body, an error is thrown. Therefore a fix for handling the undefined aspect in the body was implemented

commcare: Update request documentation for query params and fix response body error

---

tools/generate/template/src/Adaptor.js

Fixes #924 
@mtuchi points out that the new `commonRequest` doesn't use `data`, it uses `body`.

fix template request, close #924

---

.changeset/fifty-mails-melt.md
packages/gmail/CHANGELOG.md
packages/gmail/README.md
packages/gmail/package.json
packages/gmail/src/Adaptor.js

Added options.maxResults field to limit excessive data transfer.
Fixes #928
With options.query being optional, it's possible to (inadvertently) & unnecessarily process and download 10ks of messages. Now we have a default limit of 50 and a hard limit of 1000. Updated README.md with supporting documentation and an example.
know!):

Gmail adaptor - Added reasonable result limits

---

packages/googlesheets/src/Adaptor.js
packages/googlesheets/test/index.js

The `batchUpdateValues` and `append` functions return early in the event of an empty or undefined array
Fixes #576
- Added unit tests to test this functionality
- Added conditionals to check the values param

Googlesheets dont run update or append if there is no data

---

.changeset/curly-dancers-stare.md
packages/openmrs/CHANGELOG.md
packages/openmrs/ast.json
packages/openmrs/package.json
packages/openmrs/src/Adaptor.js
packages/openmrs/src/Utils.js
packages/openmrs/src/http.js
packages/openmrs/test/index.test.js
tools/build/src/util/docs-template.hbs

`post`  `remove` and `get` helpers for HTTP
Fixes #890
Added  wrappers, with tests and documentation, for http.get(), http.post() and http.remove.
know!):

Openmrs http helpers

---

packages/ghana-bdr/package.json
packages/ghana-bdr/src/mock.js
packages/ghana-bdr/src/schema/request.json
packages/ghana-nia/package.json
packages/ghana-nia/src/mock.js
packages/ghana-nia/src/schema/request.json
pnpm-lock.yaml

Experiment with JSON schema for validation
I used https://www.jsongenerator.io/schema to generate the schema. It has some problems:
- it generates an old draft 4
- I had to rename $schema to $id
- For strings it forces `minLength:1`. Maybe too strict
know!):

Ghana json schema

---

packages/dhis2/CHANGELOG.md
packages/dhis2/ast.json
packages/dhis2/package.json
packages/dhis2/src/Adaptor.js
packages/dhis2/test/index.test.js

This introduces a `findAttributeValueById(tei, uid)` function, as GHS points out that this is more durable than finding attribute values by display name (`findAttributeValue(tei, attributeDisplayName)`.
know!):

dhis2 helper: findingAttributeValuebyId

---

packages/openmrs/test/index.test.js

Refactor the OpenMRS test suite
Fixes #
Removing duplicates and storing interceptors in beforeEach blocks 
know!):

Refactored the OpenMRS test suite

---

packages/kobotoolbox/ast.json
packages/kobotoolbox/package.json
packages/kobotoolbox/src/Adaptor.js
packages/kobotoolbox/src/Utils.js
pnpm-lock.yaml

The `kobotoolbox` currently uses the old `http` implementation with `axios` and there was need to update it to the current version of `common` being used
Fixes #695 
know!):

kobotoolbox: migrate to common2.0

---

.changeset/forty-drinks-love.md
packages/kobotoolbox/src/Utils.js
packages/kobotoolbox/src/http.js
packages/kobotoolbox/src/index.js
packages/kobotoolbox/test/index.js

Implement generic name-spaced http helpers: `get`, `post` and `put`
Fixes #934 
know!):

kobotoolbox: implement generic name-spaced http methods

---

.changeset/perfect-kids-divide.md
.eslintrc.json
packages/gmail/CHANGELOG.md
packages/gmail/package.json
packages/gmail/src/Utils.js

Prior implementation was ensuring only one indicator "type" per collection which is not correct.
The goal is to have:
- all the items from contentIndicators
- all the items from defaultContentIndicators that aren't in contentIndicators
- the defaultContentIndicators should be first
This PR produces the correct calculation.
know!):

bugfix: ContentIndicator validation should be on "name", not on "type".

---

.changeset/small-cheetahs-tap.md
packages/kobotoolbox/CHANGELOG.md
packages/kobotoolbox/package.json
packages/kobotoolbox/src/Adaptor.js
packages/kobotoolbox/test/index.js

`getSubmissions()` is failing to return submission data to `state.data`.
When we added the pagination stuff, we changed the result of `util.request`. Instead of returning a Response, it returns a `{ results [] }` array when paginate is true.
This PR is a quick fix, but I'd like to look at why the unit tests didn't fail
know!):

Fix kobo submissions

---

.changeset/khaki-walls-burn.md
packages/http/ast.json
packages/http/src/Adaptor.js
packages/http/src/util.js
packages/http/test/index.js
packages/http/test/integration.js

Change signature on all `http` functions to allow body data sent separately from the `options`
Fixes #922 
know!):

http: change body signature in functions

---

.changeset/eleven-spiders-play.md
packages/openmrs/ast.json
packages/openmrs/src/Adaptor.js
packages/openmrs/src/Utils.js
packages/openmrs/src/fhir.js
packages/openmrs/src/http.js
packages/openmrs/test/index.test.js

OpenMRS docs don't currently give you a lot of help with query APIs
Fixes #492 
- add `@state` annotations to every function (including the http and fhir namespace).
- make sure the get() function makes sense and has examples of getting a list, searching a list by name, getting a single resource, and getting a subresource.
- Add a dedicated typedef for OpenMRS request params
- Remove `throw` declaration in `upsert` docbloc
- Update `upsert` examples signatures
know!):

Phase 6 improve OpenMRS adaptor docs

---

.changeset/cool-actors-argue.md
.changeset/long-parents-fly.md
packages/odoo/ast.json
packages/odoo/src/Adaptor.js

Default the `create()` function in `odoo` to  `{ }`. Update the logs to a more descriptive sentence such as `Creating a res.partner resource...` 
Fixes #1010
know!):

odoo: default `create` options to `{}` and remove logs

---

.changeset/strong-apples-stare.md
packages/odoo/src/Adaptor.js

Fix `read` docs example in `odoo` to ensure that fields in the examples are strings.
Fixes #1009
know!):

odoo: Fix `read()` docs example to show fields as string array

---

.changeset/soft-radios-fix.md
packages/http/src/util.js
packages/http/test/index.js
packages/http/test/integration.js

Remove the duplicated body from `http` response. 
Fixes #948 
When a response is received, state contains a `data` field which has the body response, but there is another duplication of the body in the `response` field in the state.
The duplicated `body` field in the `response` parameter has been removed and all related tests updated
know!):

http: remove duplicated response body

---

.changeset/great-candles-remember.md
packages/http/ast.json
packages/http/src/Adaptor.js
packages/http/src/util.js
packages/http/test/index.js
packages/http/test/integration.js

All functions in `http` allowed for the use of `callbacks` as the third option. We have stripped this and allowed users to use promise chaining instead.
Fixes #997 
All adaptor functions are being re-worked and callbacks are getting stripped. 
Since the `callbacks` have been the third option in the function, this has been removed but the same functionality can be achieved using promise chaining: 
So if you used to do this:
```js
post('/patient', { body: $.patient }, next => {
state.results.push(next.response.body);
return next;
});
```
You must edit your code to do this:
```js
post('/patient', $.patient).then(next => {
state.results.push(next.response.body);
return next;
});
```
Tests that were previously focused on testing the behaviour of callbacks have been removed as the new promise …

http:  strip callbacks

---

.changeset/curly-mirrors-appear.md
.changeset/curly-planets-laugh.md
packages/http/src/Adaptor.js
packages/http/src/util.js
packages/http/test/index.js

Replace `form` with `contentType` in `http` to allow automatic content-header configuration. 
Fixes #1005 
The `http` adaptor processes different types of data such as `xml`, `json`, and `form`.
With these different types, we need to allow users to send which type of data they are sending, but we also need to have a default one set, hence using an options `contentType` that replaces `forms`
know!):

http: control and default contentType

---

.changeset/calm-flies-listen.md
packages/common/src/util/http.js
packages/common/test/util/http.test.js

Do not parse the response body when the status code is `204`, but instead return an empty string in `state.data`
Fixes #1058 
know!):

common: return `''` when response status code is `204`

---

.changeset/green-dogs-yell.md
packages/salesforce/package.json
packages/salesforce/src/meta/helper.js
packages/salesforce/src/util.js
pnpm-lock.yaml

Update salesforce adaptor to use the latest version of `jsforcev3`
Fixes #1028
- Use jsforce node build to reduce bundle size. Update the library to `"@jsforce/jsforce-node": "^3.6.6",`
- Update `util.js` and `helper.js` to use `jsforce-node` import
- Ran integration test locally to confirm nothing is breaking 
know!):

update jsforce to v3

---

.changeset/modern-ways-share.md
.gitignore
packages/redis/ast.json
packages/redis/src/Adaptor.js
packages/redis/src/Utils.js
packages/redis/test/Adaptor.test.js

Feat #731: Add `mSet()` function to redis adaptor
Related to #739 
Add `mSet()` function, which allows you to set multiple key-value pairs at once.
know!):

feat(#731): Add mSet() function to redis adaptor

---

.changeset/warm-pots-rest.md
packages/dhis2/ast.json
packages/dhis2/package.json
packages/dhis2/src/Adaptor.js
packages/dhis2/test/index.test.js
packages/dhis2/test/integration.js
pnpm-lock.yaml

This PR extends  the work of #1059 (which was merged early)
Fixes #51 #1047 #975 #1049 #1036
This PR focused on:
- Remove `discover()` function
- Switch to `async/await`
- Bump `axios` version to `1.8.2`
- Implement better `upsert()` multiple entinties error
- Fixed `get` with `parseAs:base64`
- Update state docs in jsDoc
know!):

dhis2: Remove discover and switch to `async/await`

---

.changeset/small-countries-double.md
packages/dhis2/ast.json
packages/dhis2/src/Adaptor.js
packages/dhis2/src/index.js
packages/dhis2/src/index.ts
packages/dhis2/src/util.js
packages/dhis2/test/index.test.js

Implement a `util` namespace for non-operation helper functions
Fixes #980
Moved all the non-operation helper functions to a separate util file and can be accessed using the `fn()` block:
```
fn(state =>{
const s = util.findAttributeValueById(state.tei, 'y1w2R6leVmh');
console.log(s);
return state;
})
```
know!):

dhis2: implement `util` namespace

---

packages/openmrs/ast.json
packages/openmrs/integrations/.gitignore
packages/openmrs/integrations/upsert.js
packages/openmrs/src/Adaptor.js
packages/openmrs/test/adaptor.test.js
pnpm-lock.yaml

Playing with the upsert function I found a bunch of problems:
- Adding support for a query (as Mutchi wants) violated a few assumptions about the prior implementation
- OpenMRS returns a 404 for a record that doesn't exist - so upsert was basically failing
I've added an extra integration test around upsert and man, I gotta, say, I think upserting by query is really really sketchy. I don't particularly like what it's done to the code (way too complicated) and I don't think it's a very good deal for the user.
I'm probably going to merge it on that grounds that this is how it used to work and it's what Mutchi wants. But it's on life-support as far as I'm concerned. I might even raise an issue to remove this completely.
And then you say: if I have to have a UUID to upsert, well, it's never …

OpenMRS: rework upsert

---

.changeset/fifty-news-sing.md
packages/common/ast.json
packages/common/src/Adaptor.js
packages/common/test/index.test.js

This PR adds `log` and `debug` function in common adaptor
Fixes #496, #1117
- Add `log(...args)` function with unit tests + jsdocs examples
- Add `debug(...args)` function with unit tests + jsdocs examples
know!):

Add `log` and `debug` in common

---

.changeset/blue-lies-swim.md
.changeset/two-terms-enjoy.md
packages/common/src/util/http.js
packages/common/test/util/http.test.js
packages/http/src/util.js
packages/http/test/index.js

Various fixes around common HTTP:
* Fix an issue where HTML content does not have a stream length, so where available we prefer the content-length header
* Fix an issue where parseAs is not fed through in the http adaptor
Fixes #1155 ##1154 #1153 (lol)
know!):

Http fixes

---

.changeset/beige-penguins-pump.md
.changeset/silver-pets-dance.md
.changeset/thirty-papayas-unite.md
packages/common/ast.json
packages/common/src/Adaptor.js
packages/common/test/index.test.js
packages/mogli/src/Adaptor.js
packages/salesforce/src/Adaptor.js

This PR removes the existing `map()` operation from common.
This leaves us free to introduce a new, better map function later. See #499
know!):

common: remove map

---

packages/sftp/CHANGELOG.md
packages/sftp/configuration-schema.json
packages/sftp/package.json

Remove `format: uri` property from `configuration-schema.json`. 
Fixes #1199 
The format property enforces several requirements for a valid URI like `("http://" or "https://")`. This is not a good UX when creating `sftp` credential because it forces your `hostUrl` to be a valid URI which is not always the case. Sometimes you would want to input an ip address without `scheme/protocol`. Eg: `34.234.123.452`
know!):
- NA: If this PR includes breaking changes, do we need to …

Remove `format:uri` property from sftp configuration

---

.changeset/seven-penguins-swim.md
packages/kobotoolbox/CHANGELOG.md
packages/kobotoolbox/ast.json
packages/kobotoolbox/package.json
packages/kobotoolbox/src/Adaptor.js
packages/kobotoolbox/src/util.js
packages/kobotoolbox/test/adaptor.test.js
packages/kobotoolbox/test/helper.js
packages/kobotoolbox/test/integration.js

Add `sort` and `start` options in `getSubmission` function
Fixes #1216
- Update `getSubmission` options to include `sort` and `start` with examples
- Add `queryStringify` util function for stringify `query` and `sort` option
- Add `sortBy` function in `helper.js` to help with sorting results when `sort` param is passed
- Add unit test for `sort` and `start` option
know!):
production? Is it safe to …

`kobo` Add support for `sort` and `start` params in `getSubmission`

---

packages/fhir-4/src/datatypes.ts
packages/fhir-4/types/builders.d.ts
packages/fhir-fr/src/utils.js
packages/fhir-ndr-et/src/utils.js
tools/generate-fhir/template/src/datatypes.ts

When upgrading Docusaurus to v3, we have much stricter markdown parsing. It caught these errors in the auto-generated documentation.
With the double asterisk, we get the code above. On the old (less strict) MDX parser, it would render as this:
But now it fails with:
know!):

fix docs build by removing extra ' * '

---

packages/openmrs/test/adaptor.test.js

This PR sets up failing tests against openMRS, reproducing customer issues.
See #1233 and #1236
Note that the fails are expected on this branch, but will be resolved by subsequent PRs
know!):

OpenMRS: setup failing tests

---

.changeset/chilled-days-walk.md
packages/openmrs/src/Adaptor.js
packages/openmrs/src/Utils.js
packages/openmrs/test/adaptor.test.js

This PR tweaks the upsert logic to ensure it properly updates a resource.
Fixes #1233 
See https://community.openfn.org/t/openmrs-adapter-5-0-2-not-updating-resources/980
Using the openmrs sandbox:
```
"instanceUrl": "https://o3.openmrs.org/openmrs",
"username": "admin",
"password": "Admin123"
```
I have this code:
```
upsert(
'encounter',
{
display: 'Vitals 02/07/2024 1',
},
{
patient: 'bddfc2a9-150b-4a54-9494-1bdb18b9f91a',
encounterType: '67a71486-1a54-468f-ac3e-7091a9a79584',
limit: 1,
}
);
```
On this branch, I get this output:
```
Preparing composed upsert on encounter
GET /ws/rest/v1/encounter?patient=bddfc2a9-150b-4a54-9494-1bdb18b9f91a&encounterType=67a71486-1a54-468f-ac3e-7091a9a79584&limit=1 - 200 in 505ms
encounter/94c4a0a7-22f6-418e-b6a3-8bf57a046784 found: updating existing …
```

OpenMRS: Fix upsert logic

---

.changeset/wicked-keys-warn.md
packages/openmrs/src/Adaptor.js
packages/openmrs/test/adaptor.test.js

If doing upsert with no id in the URL, don't break the URL
Fixes #1236
know!):

Ensure upsert-create works if there's no UUID in the path

---

packages/googledrive/CHANGELOG.md
packages/kobotoolbox/ast.json
packages/kobotoolbox/src/Adaptor.js
packages/senaite/CHANGELOG.md
tools/changelog/src/update-version-histories.js

Fix import in `update-version-histories.js`, ran `pnpm update-historical-versions` and commit updated changelogs.
- Fix import in `update-version-histories.js`, 
- Ran `pnpm update-historical-versions` and commit updated changelogs.
- Update `option.limit` docs for `getSubmission() ` to say `Infinity` instead of ~Infinity~. 
know!):
- NA: Are there any unit tests? …

Fix import in `update-version-histories.js`

---

.changeset/empty-nails-push.md
.changeset/tidy-rabbits-itch.md
packages/common/src/util/http.js
packages/common/test/util/http.test.js
packages/fhir-4/src/util.ts
packages/inform/src/Utils.js

Remove `query` argument from `logResponse` and add `response.query` in `request()` function.
Fixes #1163
- Remove `query()` argument in `logResponse`
- Refactor `logResponse` to use `response.query`
- Add `resposne.query` in `request` function
- Add unit test for `response.query` in `request()` func
- Add unit test for `logResponse`
- Update `inform` and `fhir-4`  to use the improved `logResponse` function 
know!):
- NA: If this PR includes breaking changes, do we need to …

Remove `query` from `logResponse`, add `response.query` in `request()`

---

.changeset/fifty-monkeys-smash.md
packages/common/ast.json
packages/common/src/Adaptor.js
packages/common/test/index.test.js

Update `map()` to work like Array.map in js
Update documentation to reflect map changes
Fixes #499 
Change the current `map()` implementation which is similar to `each()` and make it resemble the workings of `Array.map` in js.
- The mapped result is returned as an array and mapped into `state.data`
know!):

common: update `map()` to work like Array.map

---

.changeset/happy-pets-occur.md
packages/openmrs/CHANGELOG.md
packages/openmrs/ast.json
packages/openmrs/package.json
packages/openmrs/src/Adaptor.js
packages/openmrs/src/Utils.js
packages/openmrs/test/utils.test.js

Add `language` support in `request()` util and get function 
Fixes #1246 
- Add `language` option in `get()` function and `request()` util function. The option is mapped to `Accept-Language` in headers
- Add unit test in `util.test.js`
know!):
- NA:  If this is a new adaptor, added the adaptor on marketing website ?

Add `language` support in `OpenMRS`

---

packages/mysql/src/Adaptor.js

Adds PostgreSQL-style  function for flexible SQL execution
Fixes #1245 
- Introduced a new  function to the MySQL adaptor, matching the signature and behavior of the PostgreSQL adaptor's  function.
- The new function accepts a SQL query (string or function of state), an optional options object (supporting  and ), and an optional callback.
- If  is true, the SQL statement is logged before execution.
- If  is false, the SQL is not run and is instead added to .
- The function executes the query using the MySQL connection and updates state with the results.
- This change enables OpenFn jobs to use a consistent SQL execution pattern across both MySQL and PostgreSQL adaptors.
know!): …

feat(mysql): add PostgreSQL-style  function for flexible SQL execution

---

.changeset/famous-crabs-fold.md
packages/openmrs/CHANGELOG.md
packages/openmrs/package.json
packages/openmrs/src/http.js
packages/openmrs/test/http.test.js
packages/openmrs/test/utils.test.js

Add a `put() ` helper function and fix an issue in docs, which wrongly claimed that `options.body` should be used to upload data via `http.request`
Fixes #1302
Added a very basic test of the PUT functionality.
know!):

OpenMRS: Add `put()` helper and fix a docs issue

---

.changeset/tough-eels-agree.md
packages/mssql/CHANGELOG.md
packages/mssql/package.json
packages/mssql/src/Adaptor.js

Just for background context:  `findValue()` is not returning rows when using lightning while it works just fine using CLI.  I have traced down the issue to `new Request()` function not returning `rows`. This PR provides a fix making sure rows will always be returned.
- Update `findValue()` and `queryHandler()`  function to  return rows 
- Remove duplicate `expendReferences` in `findValue`
- Code formatting 
know!):
- NA: If this PR includes breaking changes, do we need to …

`mssql` Fix `findValue` not returning rows 

---

packages/pdfshift/ast.json

Fix the failing `ast.json` file during publish for `pdfshift`
know!):

adaptors: fix ast for pdfshift

---

.changeset/kind-pets-film.md
packages/mssql/CHANGELOG.md
packages/mssql/configuration-schema.json
packages/mssql/package.json
packages/mssql/src/Adaptor.js
packages/mssql/test/integration.js

Removed `rowCollectionOnRequestCompletion` option from configuration and and reverted `tedious.Request` to include `rows` in `callback`. Also improved `AggregateError` message
Fixes #1337, #1326
- Reverted how `tedious.Request` is used to rely on its built-in row collection callback.
- Remove `rowCollectionOnRequestCompletion` from `state.configuration` and configuration schema
- Enabled `config.options.rowCollectionOnRequestCompletion = true` to ensure all rows are returned directly in the request completion callback.
- Add integration test for `insert` and `insertMany`. This helped me confirm the `queryHandler` function is still working as expected
- Improve `AggregateError` error message
- Remove unused `reject` param
Please disclose how you've used AI in this work (it's cool, we just …

`mssql` removed `rowCollectionOnRequestCompletion` from configuration

---

.changeset/thick-carrots-care.md
packages/kobotoolbox/src/http.js

Update `http.request` option docs to use `data` instead of `body` in requests
Fixes #1310
know!):

kobotoolbox: Update `http.request` body description
